#!/bin/sh
#
# dot
#
# `dot` handles installation, updates, things like that. Run it periodically
# to make sure you're on the latest and greatest.
export DOTFILES=$HOME/.dotfiles

# Make the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Make sure homebrew is installed first if we are on OS X
if test "$(uname)" = "Darwin"
then
	if test ! $(which brew)
	then
    	# Install homebrew
    	"$DOTFILES"/apps/homebrew/dotinstall.sh 2>&1
    fi
    # Update homebrew
    brew update
fi

# Find all install.sh scripts and run them iteratively
find "$DOTFILES"/apps -name dotinstall.sh | while read installer ; do sh -c "${installer}" ; done
