#!/usr/bin/env bash

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

install_git_submodules () {
  # Pull all modules
  info "pulling git submodules"
  if git submodule foreach git pull origin master
  then
    success "git submodules pulled"
  else
    fail "error pulling git submodules"
  fi
}


install_git_submodules